// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api from "./routes/api.ts";
import * as $batch_id_ from "./routes/batch/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $BatchCreate from "./islands/BatchCreate.tsx";
import * as $Events from "./islands/Events.tsx";
import * as $OverallData from "./islands/OverallData.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api.ts": $api,
    "./routes/batch/[id].tsx": $batch_id_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/BatchCreate.tsx": $BatchCreate,
    "./islands/Events.tsx": $Events,
    "./islands/OverallData.tsx": $OverallData,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
