[tool.poetry]
name = "be"
version = "0.1.0"
description = ""
authors = ["2pac <tarasyaremabcn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
